name: exploring variables and secrets

on: push

env:
    CONTAINER_REGISTRY: docker.io

    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        
        runs-on: ubuntu-latest
        steps:
        - name: docker build
          run: docker build -t $CONTAINER_REGISTRY/${{ vars.D_U }}/$IMAGE_NAME:latest

        - name: docker login
          run: docker login --username=${{ vars.D_U }} --password=${{ secrets.D_P }}

        - name: docker publish
          run: docker push $DOCKER_REGISTRY/${{ vars.D_U }}/$IMAGE_NAME:latest

    deploy:
        
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: docker run
          run: docker run -d -p 8080:80 $DOCKER_REGISTRY/${{ vars.D_U }}/$IMAGE_NAME:latest



